import { AccountRecord, PortfolioSummary, Playbook } from "./types";

export const SEED_ACCOUNTS: AccountRecord[] = [
  {
    account_id: "ACC-10492",
    company_name: "Vertex Analytics Global",
    contract_mrr: 24500,
    tenure_months: 18,
    contract_tier: "Enterprise",
    days_since_last_login: 21,
    usage_change_pct_30d: -54.2,
    open_p1_tickets: 3,
    avg_resolution_time_hrs: 44.5,
    nps_score: 3,
    csat_score: 2.1,
    payment_failures_past_quarter: 2,
    days_until_renewal: 38,
    auto_renew_enabled: 0,
    churn_probability: 0.912,
    risk_tier: "Critical",
    mrr_at_risk: 22344,
  },
  {
    account_id: "ACC-10834",
    company_name: "Hyperion Financial Systems",
    contract_mrr: 31200,
    tenure_months: 24,
    contract_tier: "Enterprise",
    days_since_last_login: 16,
    usage_change_pct_30d: -41.8,
    open_p1_tickets: 2,
    avg_resolution_time_hrs: 36.0,
    nps_score: 4,
    csat_score: 2.8,
    payment_failures_past_quarter: 1,
    days_until_renewal: 52,
    auto_renew_enabled: 0,
    churn_probability: 0.845,
    risk_tier: "Critical",
    mrr_at_risk: 26364,
  },
  {
    account_id: "ACC-10118",
    company_name: "Stratis Cloud Dynamics",
    contract_mrr: 18400,
    tenure_months: 11,
    contract_tier: "Enterprise",
    days_since_last_login: 14,
    usage_change_pct_30d: -38.5,
    open_p1_tickets: 1,
    avg_resolution_time_hrs: 28.0,
    nps_score: 5,
    csat_score: 3.2,
    payment_failures_past_quarter: 1,
    days_until_renewal: 45,
    auto_renew_enabled: 1,
    churn_probability: 0.768,
    risk_tier: "High",
    mrr_at_risk: 14131,
  },
  {
    account_id: "ACC-10992",
    company_name: "Aegis Healthcare Technologies",
    contract_mrr: 15600,
    tenure_months: 30,
    contract_tier: "Enterprise",
    days_since_last_login: 9,
    usage_change_pct_30d: -28.0,
    open_p1_tickets: 1,
    avg_resolution_time_hrs: 18.5,
    nps_score: 6,
    csat_score: 3.5,
    payment_failures_past_quarter: 0,
    days_until_renewal: 78,
    auto_renew_enabled: 1,
    churn_probability: 0.642,
    risk_tier: "High",
    mrr_at_risk: 10015,
  },
  {
    account_id: "ACC-10255",
    company_name: "Nexus Logistics Network",
    contract_mrr: 9800,
    tenure_months: 14,
    contract_tier: "Professional",
    days_since_last_login: 12,
    usage_change_pct_30d: -22.4,
    open_p1_tickets: 1,
    avg_resolution_time_hrs: 22.0,
    nps_score: 6,
    csat_score: 3.6,
    payment_failures_past_quarter: 1,
    days_until_renewal: 90,
    auto_renew_enabled: 0,
    churn_probability: 0.582,
    risk_tier: "Medium",
    mrr_at_risk: 5703,
  },
  {
    account_id: "ACC-10377",
    company_name: "Catalyst Robotics Software",
    contract_mrr: 12400,
    tenure_months: 20,
    contract_tier: "Enterprise",
    days_since_last_login: 7,
    usage_change_pct_30d: -14.2,
    open_p1_tickets: 0,
    avg_resolution_time_hrs: 12.0,
    nps_score: 7,
    csat_score: 4.0,
    payment_failures_past_quarter: 0,
    days_until_renewal: 140,
    auto_renew_enabled: 1,
    churn_probability: 0.384,
    risk_tier: "Medium",
    mrr_at_risk: 4761,
  },
  {
    account_id: "ACC-10512",
    company_name: "Pulse DataCore Solutions",
    contract_mrr: 8200,
    tenure_months: 36,
    contract_tier: "Professional",
    days_since_last_login: 4,
    usage_change_pct_30d: -5.0,
    open_p1_tickets: 0,
    avg_resolution_time_hrs: 8.0,
    nps_score: 8,
    csat_score: 4.4,
    payment_failures_past_quarter: 0,
    days_until_renewal: 180,
    auto_renew_enabled: 1,
    churn_probability: 0.215,
    risk_tier: "Low",
    mrr_at_risk: 1763,
  },
  {
    account_id: "ACC-10641",
    company_name: "Omni Cloudscale Labs",
    contract_mrr: 28000,
    tenure_months: 42,
    contract_tier: "Enterprise",
    days_since_last_login: 2,
    usage_change_pct_30d: 18.5,
    open_p1_tickets: 0,
    avg_resolution_time_hrs: 6.0,
    nps_score: 9,
    csat_score: 4.8,
    payment_failures_past_quarter: 0,
    days_until_renewal: 210,
    auto_renew_enabled: 1,
    churn_probability: 0.082,
    risk_tier: "Low",
    mrr_at_risk: 2296,
  },
  {
    account_id: "ACC-10789",
    company_name: "Nova Synthetix Global",
    contract_mrr: 19500,
    tenure_months: 28,
    contract_tier: "Enterprise",
    days_since_last_login: 1,
    usage_change_pct_30d: 26.0,
    open_p1_tickets: 0,
    avg_resolution_time_hrs: 4.5,
    nps_score: 10,
    csat_score: 5.0,
    payment_failures_past_quarter: 0,
    days_until_renewal: 260,
    auto_renew_enabled: 1,
    churn_probability: 0.045,
    risk_tier: "Low",
    mrr_at_risk: 877,
  }
];

export const SEED_SUMMARY: PortfolioSummary = {
  total_accounts: 100,
  total_portfolio_mrr: 1420500,
  total_mrr_at_risk: 284100,
  portfolio_risk_pct: 20.0,
  critical_risk_count: 8,
  high_risk_count: 14,
  medium_risk_count: 26,
  low_risk_count: 52,
};

export const SEED_PLAYBOOKS: Playbook[] = [
  {
    playbook_id: "PB-SUPP-01",
    title: "Critical Support Escalation & Technical Review",
    category: "Engineering / Support",
    priority: "P0",
    action_summary: "Escalate unresolved P1 critical tickets to VP of Engineering and organize an immediate root-cause retrospective with customer technical leads.",
    assignee_role: "VP Engineering / Senior TAM",
    sla_hours: 4,
  },
  {
    playbook_id: "PB-ENGAGE-02",
    title: "TAM Adoption & Workflow Re-Onboarding",
    category: "Customer Success",
    priority: "P1",
    action_summary: "Schedule a hands-on workflow audit with the client admin, identify dropped telemetry features, and conduct targeted enablement sessions.",
    assignee_role: "Dedicated TAM",
    sla_hours: 24,
  },
  {
    playbook_id: "PB-BILL-03",
    title: "Finance Dunning & Billing Optimization",
    category: "Finance & Operations",
    priority: "P1",
    action_summary: "Initiate white-glove dunning outreach, review payment gateway retry logs, and present flexible quarterly invoicing or wire transfer options.",
    assignee_role: "Billing Operations / AE",
    sla_hours: 12,
  },
  {
    playbook_id: "PB-RENEW-04",
    title: "Executive Sponsor Renewal Alignment",
    category: "Sales / Executive",
    priority: "P0",
    action_summary: "Schedule an urgent C-Level alignment check-in, review multi-year commercial incentives, and align product roadmap commitments ahead of renewal.",
    assignee_role: "VP Sales / Executive Sponsor",
    sla_hours: 24,
  },
  {
    playbook_id: "PB-HEALTH-05",
    title: "NPS Sentiment Recovery Outreach",
    category: "Customer Success",
    priority: "P2",
    action_summary: "Reach out to detractor stakeholders, capture qualitative feedback regarding feature blockers, and present immediate mitigation milestones.",
    assignee_role: "Customer Success Manager",
    sla_hours: 48,
  },
  {
    playbook_id: "PB-NURTURE-06",
    title: "Proactive Expansion & Value Realization",
    category: "Growth",
    priority: "P3",
    action_summary: "Deliver quarterly ROI benchmark report and propose enterprise tier tier-ups or add-on modules for expanding workloads.",
    assignee_role: "Account Executive",
    sla_hours: 72,
  },
];
